os:
  - linux
dist: trusty
cache:
  directories:
    - node_modules
sudo: false
addons:
  chrome: stable
language: node_js

node_js:
  - "12"

install:
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - git checkout -qf $TRAVIS_COMMIT

script:
  - npm run deploy:github