os:
  - linux
dist: trusty
cache:
  directories:
    - node_modules
sudo: false
addons:
  chrome: stable
# safelist to build
branches:
  only:
  - develop
language: node_js

node_js:
  - "13"

install:
  - npm install

script:
  - npm run deploy:github
